#### 석우 ver 기능 Test 
- 결론 : 요소 1,2를 yolo로 모두 구현 가능하다. 
- 물체의 움직임 안정화를 탐지하기 위해 bounding box의 좌표 변화에 대한 분산값을 활용 
- 마지막 code cell : 실시간 cam으로 연결하여 test 완료 
- TODO : 좌표 변화 idea 검증 필요

In [89]:
import requests
from PIL import Image
from ultralytics import YOLO
import cv2
import numpy as np

# load model
model = YOLO('yolov8n.pt')

# perform inference
results = model('이미지\셀카1.PNG')

# Convert the PIL segmentation mask to numpy array
segmentation_array = results[0].plot()

# Display the segmentation mask using OpenCV
cv2.imshow('YOLO Segmentation', segmentation_array)
cv2.waitKey(0)
cv2.destroyAllWindows()


image 1/1 c:\Users\james\Desktop\YOLO\이미지\셀카1.PNG: 640x640 1 person, 75.8ms
Speed: 3.0ms preprocess, 75.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)


In [ ]:
import cv2
from ultralytics import YOLO
import numpy as np

# Load YOLO model
model = YOLO('yolov8n.pt')  # Ensure the model file is accessible

# Load video file
video_path = '(334) [에필로그] 김지원 거짓말에 n년째 속고 있는 순박 청년 김수현ㅋㅋㅋ #눈물의여왕 EP.7 _ tvN 240330 방송 - YouTube 외 페이지 2개 - 개인 - Microsoft​ Edge 2024-03-31 12-42-54.mp4' 
cap = cv2.VideoCapture(video_path)

# Loop through video frames
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    # Perform prediction
    results = model(frame[:, :, ::-1])
    plots = results[0].plot()
    boxes = results[0].boxes

    for box in boxes :
        if box.cls.cpu().detach().numpy().tolist()[0] != 0 : ## 사람이 0으로 레이블 됨.
            continue
        
        x1, y1, x2, y2 = box.xyxy.cpu().detach().numpy().tolist()[0]
        xy=int(x2-x1)*int(y2-y1)
        per=int(100*xy/(frame.shape[0]*frame.shape[1]))
        print(per)
        print("현재 얼굴이 %d%%만큼 차지하고 있습니다." %per)

    if cv2.waitKey(1) & 0xFF == ord('q'):  # Break the loop if 'q' is pressed
        break
# Release resources
cap.release()
cv2.destroyAllWindows()

In [31]:
import cv2
from ultralytics import YOLO
import numpy as np

# Load YOLO model
model = YOLO('yolov8n.pt')  # Ensure the model file is accessible

# Load video file
video_path = '(334) [에필로그] 김지원 거짓말에 n년째 속고 있는 순박 청년 김수현ㅋㅋㅋ #눈물의여왕 EP.7 _ tvN 240330 방송 - YouTube 외 페이지 2개 - 개인 - Microsoft​ Edge 2024-03-31 12-42-54.mp4' 
cap = cv2.VideoCapture(video_path)

localdic={0:"왼쪽 위", 1:'위', 2:'오른쪽 위', 3:"왼쪽", 4:"가운데", 5:"오른쪽", 6:"왼쪽 아래", 7:"아래", 8:"오른쪽 아래"}
# Loop through video frames
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    # Perform prediction
    results = model(frame[:, :, ::-1])
    plots = results[0].plot()
    boxes = results[0].boxes

    for box in boxes :
        if box.cls.cpu().detach().numpy().tolist()[0] != 0 : ## 사람이 0으로 레이블 됨.
            continue
        
        x1, y1, x2, y2 = box.xyxy.cpu().detach().numpy().tolist()[0]
        x = (x1+x2)/2
        y = (y1+y2)/2
        
        loc = localdic[int(x/frame.shape[1]*3)+3*int(y/frame.shape[0]*3)]
        print(loc)
        if loc != '가운데' :
            cv2.imshow('Frame', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):  # Break the loop if 'q' is pressed
        break
# Release resources
cap.release()
cv2.destroyAllWindows()


0: 384x640 1 person, 1 tie, 53.9ms
Speed: 12.0ms preprocess, 53.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 52.9ms
Speed: 9.0ms preprocess, 52.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 49.9ms
Speed: 10.0ms preprocess, 49.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 50.9ms
Speed: 11.0ms preprocess, 50.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 53.9ms
Speed: 9.0ms preprocess, 53.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 52.9ms
Speed: 9.0ms preprocess, 52.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 54.9ms
Speed: 9.0ms preprocess, 54.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 54.9ms
Sp

In [81]:
import cv2
from ultralytics import YOLO
import numpy as np

# Load YOLO model
model = YOLO('yolov8n.pt')  # Ensure the model file is accessible

# Load video file
video_path = '(334) [에필로그] 김지원 거짓말에 n년째 속고 있는 순박 청년 김수현ㅋㅋㅋ #눈물의여왕 EP.7 _ tvN 240330 방송 - YouTube 외 페이지 2개 - 개인 - Microsoft​ Edge 2024-03-31 12-42-54.mp4' 
cap = cv2.VideoCapture(video_path)
coor=np.zeros([4,10])
vars=[]
count=0

# Loop through video frames
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    # Perform prediction
    results = model(frame[:, :, ::-1])
    plots = results[0].plot()
    boxes = results[0].boxes

    for box in boxes :
        if box.cls.cpu().detach().numpy().tolist()[0] != 0 : ## 사람이 0으로 레이블 됨.
            continue
        
        x1, y1, x2, y2 = box.xyxy.cpu().detach().numpy().tolist()[0]
        if count==0:
            coor = np.array([[x1, y1, x2, y2] for _ in range(10)]).T
            var = np.var(coor[0])/np.mean(coor[0])+np.var(coor[1])/np.mean(coor[1])+np.var(coor[2])/np.mean(coor[2])+np.var(coor[3])/np.mean(coor[3])
            vars.append(var)
            print(vars)
        elif count%5 == 0:
            coor[:, (count//5)%10] = [x1, y1, x2, y2]
            var = np.var(coor[0])/np.mean(coor[0])+np.var(coor[1])/np.mean(coor[1])+np.var(coor[2])/np.mean(coor[2])+np.var(coor[3])/np.mean(coor[3])
            vars.append(var)
            if var > 1:
                print("변했다!")
                plots=cv2.cvtColor(plots, cv2.COLOR_BGR2RGB)
                cv2.imshow("plot", plots)
                coor = np.array([[x1, y1, x2, y2] for _ in range(10)]).T
            print(vars)
            print(coor)
            break
        
    count+=1
    if cv2.waitKey(1) & 0xFF == ord('q'):  # Break the loop if 'q' is pressed
        break
# Release resources
cap.release()
cv2.destroyAllWindows()


0: 384x640 1 person, 1 tie, 52.9ms
Speed: 9.0ms preprocess, 52.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
[0.0]

0: 384x640 1 person, 1 tie, 44.9ms
Speed: 8.0ms preprocess, 44.9ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 1 tie, 49.8ms
Speed: 9.0ms preprocess, 49.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 1 tie, 50.9ms
Speed: 9.0ms preprocess, 50.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 1 tie, 52.9ms
Speed: 8.9ms preprocess, 52.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 1 tie, 44.8ms
Speed: 9.0ms preprocess, 44.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
[0.0, 0.0010149360108413536]
[[     657.03      656.77      657.03      657.03      657.03      657.03      657.03      657.03      657.03      657.03]
 [     139.25      140.05      139.25      1

In [52]:
print(count)

290


In [71]:
np.var([3,6,9])

6.0

In [63]:
np.array([1, 2, 3, 4]*10).transpose().reshape(4,10)

array([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])

In [64]:
np.array([1, 2, 3, 4]*10).transpose()

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [66]:
np.tile(np.array([1, 2, 3, 4]),10)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [3]:
import cv2
from ultralytics import YOLO
import numpy as np

# Load YOLO model
model = YOLO('yolov8s.pt')  # Ensure the model file is accessible

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

coor=np.zeros([4,10])
vars=[]
count=0

# Loop through video frames
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    # Perform prediction
    results = model(frame[:, :, ::-1])
    plots = results[0].plot()
    boxes = results[0].boxes

    for box in boxes :
        if box.cls.cpu().detach().numpy().tolist()[0] != 0 : ## 사람이 0으로 레이블 됨.
            continue
        
        x1, y1, x2, y2 = box.xyxy.cpu().detach().numpy().tolist()[0]
        if count==0:
            coor = np.array([[x1, y1, x2, y2] for _ in range(10)]).T
            var = np.var(coor[0])/np.mean(coor[0])+np.var(coor[1])/np.mean(coor[1])+np.var(coor[2])/np.mean(coor[2])+np.var(coor[3])/np.mean(coor[3])
            vars.append(var)
            print(vars)
        elif count%5 == 0:
            coor[:, (count//5)%10] = [x1, y1, x2, y2]
            var = np.var(coor[0])/np.mean(coor[0])+np.var(coor[1])/np.mean(coor[1])+np.var(coor[2])/np.mean(coor[2])+np.var(coor[3])/np.mean(coor[3])
            vars.append(var)
            if var > 1:
                print("변했다!")
                #plots=cv2.cvtColor(plots, cv2.COLOR_BGR2RGB)
                #cv2.imshow("plot", plots)
                cv2.putText(frame,"moved",(20,200),cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)
                coor = np.array([[x1, y1, x2, y2] for _ in range(10)]).T
            print(vars)
            print(coor)
            break
        
    count+=1
    cv2.imshow('frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):  # Break the loop if 'q' is pressed
        break
# Release resources
cap.release()
cv2.destroyAllWindows()


0: 384x640 1 person, 328.9ms
Speed: 12.6ms preprocess, 328.9ms inference, 3.4ms postprocess per image at shape (1, 3, 384, 640)
[0.0]

0: 384x640 1 person, 322.2ms
Speed: 12.1ms preprocess, 322.2ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 295.4ms
Speed: 13.7ms preprocess, 295.4ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 280.2ms
Speed: 12.3ms preprocess, 280.2ms inference, 2.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 256.9ms
Speed: 11.0ms preprocess, 256.9ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 265.8ms
Speed: 10.2ms preprocess, 265.8ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)
[0.0, 0.012974693084927187]
[[     601.92      610.22      601.92      601.92      601.92      601.92      601.92      601.92      601.92      601.92]
 [     186.15      188.17      186.15      186.15      186.15      18