In [1]:
# !pip install ultralytics

     ---------------------------------------- 0.0/40.3 kB ? eta -:--:--
     ------------------- ------------------ 20.5/40.3 kB 682.7 kB/s eta 0:00:01
     -------------------------------------- 40.3/40.3 kB 485.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/723.3 kB ? eta -:--:--
   --- ------------------------------------ 61.4/723.3 kB 1.7 MB/s eta 0:00:01
   ------------ --------------------------- 225.3/723.3 kB 2.8 MB/s eta 0:00:01
   ---------------------- ----------------- 409.6/723.3 kB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 723.3/723.3 kB 4.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   ---------------------------------------- 0.2/38.6 MB 12.2 MB/s eta 0:00:04
   ---------------------------------------- 0.2/38.6 MB 12.2 MB/s eta 0:00:04
   - -------------------------------------- 1.3/38.6 MB 10.4 MB/s eta 0:00:04
   - -------------------------------------- 1.8/38.6 MB 10.2 MB/s eta 0:00

In [89]:
import requests
from PIL import Image
from ultralytics import YOLO
import cv2
import numpy as np

# load model
model = YOLO('yolov8n.pt')

# perform inference
results = model('이미지\셀카1.PNG')

# Convert the PIL segmentation mask to numpy array
segmentation_array = results[0].plot()

# Display the segmentation mask using OpenCV
cv2.imshow('YOLO Segmentation', segmentation_array)
cv2.waitKey(0)
cv2.destroyAllWindows()


image 1/1 c:\Users\james\Desktop\YOLO\이미지\셀카1.PNG: 640x640 1 person, 75.8ms
Speed: 3.0ms preprocess, 75.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)


In [39]:
import cv2
from ultralytics import YOLO
import numpy as np

# Load YOLO model
model = YOLO('yolov8n.pt')  # Ensure the model file is accessible

# Load video file
video_path = '(334) [에필로그] 김지원 거짓말에 n년째 속고 있는 순박 청년 김수현ㅋㅋㅋ #눈물의여왕 EP.7 _ tvN 240330 방송 - YouTube 외 페이지 2개 - 개인 - Microsoft​ Edge 2024-03-31 12-42-54.mp4' 
cap = cv2.VideoCapture(video_path)

# Loop through video frames
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    # Perform prediction
    results = model(frame[:, :, ::-1])
    plots = results[0].plot()
    boxes = results[0].boxes

    for box in boxes :
        if box.cls.cpu().detach().numpy().tolist()[0] != 0 : ## 사람이 0으로 레이블 됨.
            continue
        
        x1, y1, x2, y2 = box.xyxy.cpu().detach().numpy().tolist()[0]
        xy=int(x2-x1)*int(y2-y1)
        per=int(100*xy/(frame.shape[0]*frame.shape[1]))
        print(per)
        print("현재 얼굴이 %d%%만큼 차지하고 있습니다." %per)

    if cv2.waitKey(1) & 0xFF == ord('q'):  # Break the loop if 'q' is pressed
        break
# Release resources
cap.release()
cv2.destroyAllWindows()


0: 384x640 1 person, 1 tie, 51.9ms
Speed: 9.0ms preprocess, 51.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
46
현재 얼굴이 46%만큼 차지하고 있습니다.

0: 384x640 1 person, 1 tie, 51.9ms
Speed: 9.0ms preprocess, 51.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
46
현재 얼굴이 46%만큼 차지하고 있습니다.

0: 384x640 1 person, 1 tie, 51.9ms
Speed: 12.0ms preprocess, 51.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
45
현재 얼굴이 45%만큼 차지하고 있습니다.

0: 384x640 1 person, 1 tie, 52.9ms
Speed: 9.0ms preprocess, 52.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
45
현재 얼굴이 45%만큼 차지하고 있습니다.

0: 384x640 1 person, 1 tie, 49.9ms
Speed: 12.0ms preprocess, 49.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
45
현재 얼굴이 45%만큼 차지하고 있습니다.

0: 384x640 1 person, 1 tie, 49.9ms
Speed: 11.0ms preprocess, 49.9ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)
45
현재 얼굴이 45%만큼 차지하고 있습니다.

0: 384x640 1 person, 1 tie, 52.9ms
S

In [31]:
import cv2
from ultralytics import YOLO
import numpy as np

# Load YOLO model
model = YOLO('yolov8n.pt')  # Ensure the model file is accessible

# Load video file
video_path = '(334) [에필로그] 김지원 거짓말에 n년째 속고 있는 순박 청년 김수현ㅋㅋㅋ #눈물의여왕 EP.7 _ tvN 240330 방송 - YouTube 외 페이지 2개 - 개인 - Microsoft​ Edge 2024-03-31 12-42-54.mp4' 
cap = cv2.VideoCapture(video_path)

localdic={0:"왼쪽 위", 1:'위', 2:'오른쪽 위', 3:"왼쪽", 4:"가운데", 5:"오른쪽", 6:"왼쪽 아래", 7:"아래", 8:"오른쪽 아래"}
# Loop through video frames
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    # Perform prediction
    results = model(frame[:, :, ::-1])
    plots = results[0].plot()
    boxes = results[0].boxes

    for box in boxes :
        if box.cls.cpu().detach().numpy().tolist()[0] != 0 : ## 사람이 0으로 레이블 됨.
            continue
        
        x1, y1, x2, y2 = box.xyxy.cpu().detach().numpy().tolist()[0]
        x = (x1+x2)/2
        y = (y1+y2)/2
        
        loc = localdic[int(x/frame.shape[1]*3)+3*int(y/frame.shape[0]*3)]
        print(loc)
        if loc != '가운데' :
            cv2.imshow('Frame', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):  # Break the loop if 'q' is pressed
        break
# Release resources
cap.release()
cv2.destroyAllWindows()


0: 384x640 1 person, 1 tie, 53.9ms
Speed: 12.0ms preprocess, 53.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 52.9ms
Speed: 9.0ms preprocess, 52.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 49.9ms
Speed: 10.0ms preprocess, 49.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 50.9ms
Speed: 11.0ms preprocess, 50.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 53.9ms
Speed: 9.0ms preprocess, 53.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 52.9ms
Speed: 9.0ms preprocess, 52.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 54.9ms
Speed: 9.0ms preprocess, 54.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
가운데

0: 384x640 1 person, 1 tie, 54.9ms
Sp

In [81]:
import cv2
from ultralytics import YOLO
import numpy as np

# Load YOLO model
model = YOLO('yolov8n.pt')  # Ensure the model file is accessible

# Load video file
video_path = '(334) [에필로그] 김지원 거짓말에 n년째 속고 있는 순박 청년 김수현ㅋㅋㅋ #눈물의여왕 EP.7 _ tvN 240330 방송 - YouTube 외 페이지 2개 - 개인 - Microsoft​ Edge 2024-03-31 12-42-54.mp4' 
cap = cv2.VideoCapture(video_path)
coor=np.zeros([4,10])
vars=[]
count=0

# Loop through video frames
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    # Perform prediction
    results = model(frame[:, :, ::-1])
    plots = results[0].plot()
    boxes = results[0].boxes

    for box in boxes :
        if box.cls.cpu().detach().numpy().tolist()[0] != 0 : ## 사람이 0으로 레이블 됨.
            continue
        
        x1, y1, x2, y2 = box.xyxy.cpu().detach().numpy().tolist()[0]
        if count==0:
            coor = np.array([[x1, y1, x2, y2] for _ in range(10)]).T
            var = np.var(coor[0])/np.mean(coor[0])+np.var(coor[1])/np.mean(coor[1])+np.var(coor[2])/np.mean(coor[2])+np.var(coor[3])/np.mean(coor[3])
            vars.append(var)
            print(vars)
        elif count%5 == 0:
            coor[:, (count//5)%10] = [x1, y1, x2, y2]
            var = np.var(coor[0])/np.mean(coor[0])+np.var(coor[1])/np.mean(coor[1])+np.var(coor[2])/np.mean(coor[2])+np.var(coor[3])/np.mean(coor[3])
            vars.append(var)
            if var > 1:
                print("변했다!")
                plots=cv2.cvtColor(plots, cv2.COLOR_BGR2RGB)
                cv2.imshow("plot", plots)
                coor = np.array([[x1, y1, x2, y2] for _ in range(10)]).T
            print(vars)
            print(coor)
            break
        
    count+=1
    if cv2.waitKey(1) & 0xFF == ord('q'):  # Break the loop if 'q' is pressed
        break
# Release resources
cap.release()
cv2.destroyAllWindows()


0: 384x640 1 person, 1 tie, 52.9ms
Speed: 9.0ms preprocess, 52.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
[0.0]

0: 384x640 1 person, 1 tie, 44.9ms
Speed: 8.0ms preprocess, 44.9ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 1 tie, 49.8ms
Speed: 9.0ms preprocess, 49.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 1 tie, 50.9ms
Speed: 9.0ms preprocess, 50.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 1 tie, 52.9ms
Speed: 8.9ms preprocess, 52.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 1 tie, 44.8ms
Speed: 9.0ms preprocess, 44.8ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
[0.0, 0.0010149360108413536]
[[     657.03      656.77      657.03      657.03      657.03      657.03      657.03      657.03      657.03      657.03]
 [     139.25      140.05      139.25      1

In [52]:
print(count)

290


In [71]:
np.var([3,6,9])

6.0

In [63]:
np.array([1, 2, 3, 4]*10).transpose().reshape(4,10)

array([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])

In [64]:
np.array([1, 2, 3, 4]*10).transpose()

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [66]:
np.tile(np.array([1, 2, 3, 4]),10)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])